// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ipftakvpodctnsdnnjhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwZnRha3Zwb2RjdG5zZG5uamhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzNDIxMDEsImV4cCI6MjA3NTkxODEwMX0.mnZtvXFNxEK8RHdgqmJV15QG0-Mr56VHQt10iIH_0U0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);